bookowl/urls.py
from django.conf.urls import url
from bookowl import views

app_name = 'bookowl'

urlpatterns = [
    url(r'^$', views.EventsView.as_view(), name='show_events'),
    url(r'^add_authors/$', views.AddAuthorsView.as_view(), name='add_authors'),
    url(r'^calibre/$', views.UploadCsv.as_view(), name='calibre'),
    url(r'^show_authors/$', views.AuthorsView.as_view(), name='show_authors'),
    url(r'^recommendations/$', views.EventsView.as_view(), name='recommendations'),
]

eventowl/urls.py
from django.conf.urls import url
from eventowl import views

app_name = 'eventowl'

urlpatterns = [
    url(r"^$", views.ChoiceView.as_view(), name="choice"),
    url(r"^impressum/$", views.ImpressumView.as_view(), name="impressum"),
    url(r"^about/$", views.AboutView.as_view(), name="about"),
    url(r"^ical/$", views.ICalView.as_view(), name="ical"),
    url(
        r"^account/signup/$",
        views.SignupView.as_view(),
        name="account_signup"
    ),
    url(
        r"^account/settings/$",
        views.SettingsView.as_view(),
        name="account_settings"
    ),
    url(r'^feed/(?P<uuid>[\da-f-]+)/$',
        views.NotificationsFeed(), name="feed"),
    url(r'^calendar/(?P<uuid>[\da-f-]+)/$',
        views.CalendarView.as_view(), name="calendar"),
]

eventowlproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from notifications import urls as notification_urls

urlpatterns = [
    url(r'^', include('eventowl.urls', 'eventowl')),
    url(r'^artists/', include('concertowl.urls', 'concertowl')),
    url(r'^books/', include('bookowl.urls', 'bookowl')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^account/', include('account.urls')),
    url('^inbox/notifications/', include(notification_urls, namespace='notifications')),
]

bookowl/models.py
from django.db import models
from django.contrib.auth.models import User
from eventowl import models as base_models


class Author(models.Model):
    name = models.CharField(max_length=200)
    subscribers = models.ManyToManyField(User, related_name='authors')
    recommendedtos = models.ManyToManyField(User, through='RecommendedAuthor')
    favoritedby = models.ManyToManyField(User, related_name='favorit_authors')

    def __str__(self):
        return self.name


class RecommendedAuthor(models.Model):
    artist = models.ForeignKey(Author, related_name="recommendation", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField(null=True)


class Book(models.Model):
    title = models.CharField(max_length=300)
    isbn = models.CharField(max_length=20, null=True)
    date = models.DateField()
    buy_url = models.URLField(max_length=300)
    authors = models.ManyToManyField(Author, related_name='books')

    def __str__(self):
        author_names = [author.name.title() for author in
                        self.authors.all()]
        name = "{} by {} released on {}".format(self.title,
                                                 ", ".join(author_names),
                                                 str(self.date.strftime("%Y-%m-%d")))
        return name


class Preview(base_models.Preview):
    pass

bookowl/forms.py
from eventowlproject import settings
from eventowl.forms import RestrictedFileField

from django import forms

class UploadFileForm(forms.Form):
    authors = RestrictedFileField(content_types=['text/csv'],
                                  max_upload_size=settings.MAX_UPLOAD_SIZE)

bookowl/views.py
import csv
from io import StringIO

from django.views.generic import FormView
from django.urls import reverse

from .models import Book, Author
from eventowl import views as baseviews
from eventowl.utils.string_helpers import normalize
from bookowl.management.commands.update_releases import ReleaseConnector
from bookowl.forms import UploadFileForm
from bookowl.tasks import update_recommended_authors


class EventsView(baseviews.EventsView):
    template_name = 'bookowl/show_events_table.html'
    event_model = Book
    originator_model = Author
    originator_name = 'authors'


def _update_authors(new_authors, user):
    added_authors = []
    for new_author in new_authors:
        new_author = normalize(new_author)
        author, created = Author.objects.get_or_create(name=new_author)
        if created:
            added_authors.append(new_author)
            author.save()
        author.subscribers.add(user)
    con = ReleaseConnector()
    con.update_events(added_authors)


class AddAuthorsView(baseviews.AddView):
    template_name = 'bookowl/add_authors.html'

    def update_func(self, *args, **kwargs):
        return _update_authors(*args, **kwargs)


def _parse_csv(request):
    author_stream = StringIO(
        request.FILES["authors"].read().decode('utf-8-sig'))
    reader = csv.DictReader(author_stream, delimiter=';')
    try:
        authors = {row['authors'] for row in reader}
    except KeyError:
        authors = set()
    return authors


class UploadCsv(FormView):
    template_name = 'bookowl/upload_csv.html'
    form_class = UploadFileForm

    def form_valid(self, form):
        authors = _parse_csv(self.request)
        self.authors = authors
        _update_authors(authors, self.request.user)
        return super(UploadCsv, self).form_valid(form)

    def get_success_url(self):
        return reverse('bookowl:calibre')


class AuthorsView(baseviews.OriginatorView):
    template_name = 'bookowl/show_authors.html'
    context_object_name = 'authors'
    update_recommendation_func = update_recommended_authors
    originator_model = Author

bookowl/templates/bookowl/add_authors.html
{% extends 'bookowl/base.html' %}
{% block content %}

<legend>Add new authors manually. Fits this old school medium just fine.</legend>
<form action="{% url 'bookowl:add_authors' %}" method="get">
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-book"></i></span>
      <input id="id_filter"
           class="form-control"
           placeholder="New author..."
           name="add"
           type="text">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Add!</button>
      </span>
    </div>
</form>

{% if request.GET.add %}
Sucesfully added {{ request.GET.add|title }}. Maybe this author is releasing a <a href="{% url 'bookowl:show_events' %}">book</a> soon?
{% endif %}

{% endblock content %}

bookowl/templates/bookowl/base.html
{% extends 'eventowl/common_base.html' %}
{% load static %}


{% block extra_header %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-book-theme.css' %}">
    <link rel="stylesheet" href="{% static 'bookowl.css' %}">
    <meta name="theme-color" content="#c4781b">
{% endblock extra_header %}


{% block navbar_style %}
    navbar-default
{% endblock navbar_style%}


{% block navbar_title %}
    <a href="/" class="pull-left"><img src="{% static 'icons/eventowl-white.png' %}"></a>
    <a style="padding:15 0 10 10; margin:0;" class="navbar-brand" href="/">EventOwl/</a>
    <a style="padding:15 10 10 0; margin:0;" class="navbar-brand" href="{% url 'bookowl:show_events' %}">BookOwl</a>
{% endblock navbar_title %}


{% block navbar %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Add authors <b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'bookowl:add_authors' %}">Manually</a></li>
            <li><a href="{% url 'bookowl:calibre' %}">Calibre</a></li>
            <li><a href="{% url 'bookowl:recommendations' %}">Recommendations</a></li>
        </ul>
    </li>
    <li><a href="{% url 'bookowl:show_authors' %}">Show Authors</a></li>
    <li><a href="{% url 'bookowl:show_events' %}">Show Releases</a></li>
{% endblock navbar %}

bookowl/templates/bookowl/show_authors.html
{% extends 'bookowl/base.html' %}
{% block content %}

<legend>Have a look at all your subscribed authors.</legend>
<form action="{% url 'bookowl:show_authors' %}" method="get">
    {% include "eventowl/filter.html"%}
</form>

{% if authors %}
    <ul class="list-group">
    {% for author in authors %}
        <li class="list-group-item">
	        {{ author.name|title }}
	        <button type="button" class="btn btn-xs pull-right" name="remove" value="{{ author.name }}" onclick="$.get(window.location.pathname + '?remove={{ author.name|urlencode }}'); $(this).parent().hide()">
	            <span class="glyphicon glyphicon-remove"></span>
	        </button>

            <button type="button" id="unfavorite_{{ forloop.counter }}" class="btn btn-xs pull-right" name="unfavorite" value="{{ author.name }}" onclick="$.get(window.location.pathname + '?unfavorite={{ author.name|urlencode }}'); $(this).hide(); $('#favorite_{{ forloop.counter }}').show()">
                 <font color="DarkOrange"><span class="glyphicon glyphicon-star"></span></font>
            </button>

            <button type="button" id="favorite_{{ forloop.counter }}" class="btn btn-xs pull-right" name="favorite" value="{{ artist.name }}" onclick="$.get(window.location.pathname + '?favorite={{ author.name|urlencode }}'); $(this).hide(); $('#unfavorite_{{ forloop.counter }}').show()">
                 <span class="glyphicon glyphicon-star"></span>
            </button>
            {% if author in favorites %}
                <script>$('#favorite_{{ forloop.counter }}').hide()</script>
            {% else %}
                <script>$('#unfavorite_{{ forloop.counter }}').hide()</script>
	        {% endif %}
        </li>
    {% endfor %}
    </ul>
{% include "eventowl/pagination.html"%}

{% else %}
    {% if request.GET.name_filter%}
        <p>No authors matching '{{ request.GET.name_filter }}'.</p>
    {% else %}
        <p>You are not subscribed to any authors yet. Add some :)</p>
    {% endif %}
{% endif %}

{% endblock content %}

bookowl/templates/bookowl/show_events_table.html
{% extends 'bookowl/base.html' %}
{% load common_tags %}

{% block content %}
<legend>All new book releases. We hope you find something nice.</legend>

<form action="{% url 'bookowl:show_events' %}" method="get">
    {% include "eventowl/filter.html"%}
</form>

{% if events %}
    <table class="table table-hover table-striped" id=events-table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Title</th>
                <th>Authors</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for event in events %}
                <tr>
                    <td>{{event.date|date}}</td>
                    <td>{{event.title|title}}</td>
                    <td>
                        {% for author in event.authors.all %}
                            {{ author|title }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{% url 'eventowl:ical' %}?start_date={{ event.date|date:'U' }}&summary={{ event.title|title }}&whole_day=1"
                           class="btn btn-xs pull-right" name="ical">
		    	            <span class="fa fa-calendar"></span>
                        </a>
		            </td>
                </tr>
                <tr>
                    <td colspan="4">
                        {% for author in event.authors.all %}
                            {{ author|title }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                        will release a new book on {{event.date|date}}.<br>
                        It's going to be called '{{event.title|title}}'.<br>
                        You can buy it <a href={{event.buy_url}} target="_blank">here</a>. Enjoy!
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


    <script type="text/javascript">
    $('#events-table').jExpand();
    </script>

    {% include "eventowl/pagination.html" %}
{% else %}
    {% if request.GET|get_item:'name_filter'|default:'' %}
        <p>No events matching '{{ request.GET.name_filter }}'.</p>
    {% else %}
        <p>Your subscribed authors don't release any books anytime soon :(</p>
    {% endif %}
{% endif %}

{% endblock content %}

bookowl/templates/bookowl/upload_csv.html
{% extends 'bookowl/base.html' %}
{% load widget_tweaks %}
{% load common_tags %}
{% load static%}

{% block content %}
<legend>Upload a csv file with new authors. Nice idea.</legend>
{% settings_value "MAX_UPLOAD_SIZE_MB" as upload_max_mb %}
<p>This file should be in csv format (columns separated by ; if you really need more than one) and contain a column called 'authors'. Please keep it under {{upload_max_mb}}MB, it's appreciated.</p>
<p>You can create a file just like this using calibre:
<ol>
    <li>Click the dropdown arrow right next to 'convert books'</li>
    <li>Choose the very concisely named 'Create a catalog of the books in your calibre library'</li>
    <li>Choose CSV as 'catalog format'</li>
    <li>In 'CSV/XML settings' make sure at least 'authors' is selected</li>
    <li>Click OK and voila. Wasn't that hard, was it?</li>
</ol>
</p>
<form class="form-inline" enctype="multipart/form-data" method="post" action="{% url 'bookowl:calibre' %}">
{% csrf_token %}
<div class="form-group">
<script src="{% static 'jquery/bootstrap-filestyle.min.js' %}"></script>
<div class="input-group">
    {{ form.authors|add_class:"filestyle"}}
</div>
<button type="submit" class="btn btn-primary">Upload</button>
</form>

{% if form.errors %}
<p><i>Could not upload file: {{ form.errors.authors|striptags }}</i></p>
{% endif %}

{%endblock content %}