bookowl/urls.py
from django.conf.urls import url
from bookowl import views

app_name = 'bookowl'

urlpatterns = [
    url(r'^$', views.EventsView.as_view(), name='show_events'),
    url(r'^add_authors/$', views.AddAuthorsView.as_view(), name='add_authors'),
    url(r'^calibre/$', views.UploadCsv.as_view(), name='calibre'),
    url(r'^show_authors/$', views.AuthorsView.as_view(), name='show_authors'),
    url(r'^recommendations/$', views.EventsView.as_view(), name='recommendations'),
]

concertowl/urls.py
from django.conf.urls import url
from concertowl import views

app_name = 'concertowl'

urlpatterns = [
    url(r'^upload_json/$', views.upload_json, name='upload_json'),
    url(r'^upload_local/$', views.UploadLocalView.as_view(), name='upload_local'),
    url(r'^spotify/$', views.spotify, name='spotify'),
    url(r'^show_artists/$', views.ArtistsView.as_view(), name='show_artists'),
    url(r'^show_records/$', views.RecordsView.as_view(), name='show_records'),
    url(r'^add_artists/$', views.AddArtistsView.as_view(), name='add_artists'),
    url(r'^recommendations/$', views.RecommendationsView.as_view(),
        name='recommendations'),
    url(r'^$', views.EventsView.as_view(), name='show_events'),
]

eventowl/urls.py
from django.conf.urls import url
from eventowl import views

app_name = 'eventowl'

urlpatterns = [
    url(r"^$", views.ChoiceView.as_view(), name="choice"),
    url(r"^impressum/$", views.ImpressumView.as_view(), name="impressum"),
    url(r"^about/$", views.AboutView.as_view(), name="about"),
    url(r"^ical/$", views.ICalView.as_view(), name="ical"),
    url(
        r"^account/signup/$",
        views.SignupView.as_view(),
        name="account_signup"
    ),
    url(
        r"^account/settings/$",
        views.SettingsView.as_view(),
        name="account_settings"
    ),
    url(r'^feed/(?P<uuid>[\da-f-]+)/$',
        views.NotificationsFeed(), name="feed"),
    url(r'^calendar/(?P<uuid>[\da-f-]+)/$',
        views.CalendarView.as_view(), name="calendar"),
]

eventowlproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from notifications import urls as notification_urls

urlpatterns = [
    url(r'^', include('eventowl.urls', 'eventowl')),
    url(r'^artists/', include('concertowl.urls', 'concertowl')),
    url(r'^books/', include('bookowl.urls', 'bookowl')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^account/', include('account.urls')),
    url('^inbox/notifications/', include(notification_urls, namespace='notifications')),
]

eventowl/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    city = models.CharField(max_length=200)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.user.username


class Preview(models.Model):
    image = models.URLField(max_length=200, unique=True)
    description = models.TextField()
    link = models.URLField(max_length=200)
    alttext = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        get_latest_by = 'updated_at'

    def __str__(self):
        return self.description


class VisitorLocation(models.Model):
    country = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)

    def __str__(self):
        return '{} - {}'.format(self.city, self.country)

eventowl/forms.py
from django.template.defaultfilters import filesizeformat
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User
from account import forms as account_forms

from eventowlproject import settings


class RestrictedFileField(forms.FileField):

    def __init__(self, *args, **kwargs):
        self.content_types = kwargs.pop("content_types")
        self.content_types.append("application/octet-stream")
        self.max_upload_size = kwargs.pop("max_upload_size")

        forms.FileField.__init__(self, *args, **kwargs)

    def clean(self, data, initial=None):
        afile = forms.FileField.clean(self, data, initial)

        try:
            content_type = afile.content_type
            if content_type in self.content_types:
                if afile._size > self.max_upload_size:
                    raise ValidationError('Please keep filesize under %s. Current filesize %s' % (
                        filesizeformat(self.max_upload_size), filesizeformat(afile._size)))
            else:
                raise ValidationError('Filetype not supported.')
        except AttributeError:
            pass

        return data


class SignupForm(account_forms.SignupForm):
    city = forms.CharField(max_length=200)


class SettingsForm(forms.Form):
    city = forms.CharField(max_length=200)
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(SettingsForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(SettingsForm, self).clean()
        email = cleaned_data.get("email")
        if (email.lower() != self.user.email.lower() and
                User.objects.filter(email__iexact=email).exists()):
            raise ValidationError('E-mail already in use.')
        return cleaned_data

eventowl/views.py
from datetime import date, timedelta

import icalendar
import notifications
from django.contrib.syndication.views import Feed
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic import TemplateView, ListView, FormView, View
from account import views as account_views

from concertowl.models import Event, Artist
from eventowl.models import UserProfile, VisitorLocation
from eventowl.forms import SignupForm, SettingsForm
from eventowl.utils.dates_and_times import ical_event
from eventowl.utils.string_helpers import as_filename
from eventowlproject import settings
from eventowl import app_previews
from eventowl.utils.location import current_position
from eventowl.utils.user_agents import is_robot
from eventowlproject.settings import DATABASES


class ChoiceView(TemplateView):
    template_name = 'eventowl/choice.html'


class CustomListView(ListView):
    paginate_by = settings.PAGINATION_SIZE

    def _filtered_and_sorted(self, name_filter, user):
        raise NotImplementedError

    def get_queryset(self):
        name_filter = self.request.GET.get("name_filter", "")
        return self._filtered_and_sorted(name_filter, self.request.user)


def _subscribed_events(originator_model, originator_name, event_model, user, name_filter='', override_days_back=None):
    subscribed_originators = originator_model.objects.filter(subscribers=user,
                                                             name__icontains=name_filter)

    days_back = override_days_back if override_days_back is not None else settings.DAYS_BACK
    oldest_shown = date.today() - timedelta(days=days_back)

    kwargs = {originator_name + '__in': subscribed_originators,
              'date__gte': oldest_shown}
    subscribed_events = event_model.objects.filter(**kwargs).distinct()
    return subscribed_events.order_by("date").distinct()


class EventsView(CustomListView):
    template_name = None
    context_object_name = 'events'
    event_model = None
    originator_model = None
    originator_name = None
    override_days_back = None

    def _filtered_and_sorted(self, name_filter, user):
        return _subscribed_events(self.originator_model, self.originator_name, self.event_model,
                                  user, name_filter, self.override_days_back)


class AddView(TemplateView):
    template_name = None

    def get(self, request):
        add_originator = request.GET.get('add')
        if add_originator is not None:
            self.update_func(add_originator.split(','), request.user)
        return TemplateView.get(self, request)


class OriginatorView(CustomListView):
    template_name = None
    context_object_name = None
    originator_model = None
    order_by = 'name'

    def get(self, request):
        unsubscribe = request.GET.get("remove")
        if unsubscribe is not None:
            self._unsubscribe(unsubscribe, request.user)

        favorite = request.GET.get("favorite")
        if favorite is not None:
            self._favorite(favorite, request.user)

        unfavorite = request.GET.get("unfavorite")
        if unfavorite is not None:
            self._unfavorite(unfavorite, request.user)

        return CustomListView.get(self, request)

    def get_context_data(self, **kwargs):
        context = CustomListView.get_context_data(self, **kwargs)
        context['favorites'] = self.originator_model.objects.filter(
            favoritedby=self.request.user)
        return context

    def _filtered_and_sorted(self, name_filter, user):
        subscribed_originators = self.originator_model.objects.filter(subscribers=user,
                                                                      name__icontains=name_filter)
        return subscribed_originators.order_by(self.order_by)

    def _update_recommendations(self, user):
        objs = [o.name for o in self.originator_model.objects.filter(
            favoritedby=user)]
        self.update_recommendation_func.delay(objs, user.username)

    def _unfavorite(self, originator, user):
        try:
            obj = self.originator_model.objects.get(name=originator)
            obj.favoritedby.remove(user)
            self._update_recommendations(user)
        except self.originator_model.DoesNotExist:
            pass

    def _unsubscribe(self, originator, user):
        try:
            obj = self.originator_model.objects.get(name=originator)
            obj.subscribers.remove(user)
            self._unfavorite(originator, user)
        except self.originator_model.DoesNotExist:
            pass

    def _favorite(self, originator, user):
        obj = self.originator_model.objects.get(name=originator)
        obj.favoritedby.add(user)
        self._update_recommendations(user)


class ImpressumView(TemplateView):
    template_name = 'eventowl/impressum.html'


class AboutView(TemplateView):
    template_name = 'eventowl/about.html'


def _get_location(request):
    city, country = current_position(request)
    if city is None and country is None:
        city = 'new york'
        country = 'new york'

    return city, country


def _save_location(city, country, request):
    if not is_robot(request):
        VisitorLocation.objects.update_or_create(city=city,
                                                 country=country)


class SignupView(account_views.SignupView):
    form_class = SignupForm

    def get_context_data(self, **kwargs):
        city, country = _get_location(self.request)
        _save_location(city, country, self.request)

        kwargs['previews'] = app_previews.get_all_objects({'city': city,
                                                           'country': country})
        return super(SignupView, self).get_context_data(**kwargs)

    def after_signup(self, form):
        self.create_profile(form)
        super(SignupView, self).after_signup(form)

    def create_profile(self, form):
        UserProfile.objects.update_or_create(user=self.created_user,
                                             city=form.cleaned_data["city"])


class SettingsView(FormView):
    template_name = 'account/settings.html'
    form_class = SettingsForm
    success_url = '/account/settings'

    def get_initial(self):
        initial = super(SettingsView, self).get_initial()
        initial['email'] = self.request.user.email
        initial['city'] = self.request.user.userprofile.city
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.email = form.cleaned_data['email']

        old_city = user.userprofile.city
        new_city = form.cleaned_data['city']
        user.userprofile.city = new_city

        user.save()
        user.userprofile.save()

        if old_city != new_city:
            subscribed_artists = [artist.name for artist in user.artists.all()]
            # update_events(subscribed_artists, [new_city]) TODO: do in subclass

        return super(SettingsView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(SettingsView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class ICalView(View):
    def get(self, request):
        get_params = request.GET
        start_time = get_params.get('start_time')
        start_date = get_params.get('start_date')
        duration = get_params.get('duration')
        whole_day = get_params.get('whole_day') == '1'
        location = get_params.get('location')
        summary = get_params.get('summary')
        description = get_params.get('description')
        filename = as_filename(summary) + '.ics' if summary else 'cal.ics'
        istring = ical_event(start_date, start_time, duration, location,
                             summary, description, whole_day=whole_day).to_ical()

        response = HttpResponse(istring, content_type='text/calendar')
        response['Filename'] = filename
        response['Content-Disposition'] = 'attachment; filename={}'.format(
            filename)
        return response


class NotificationsFeed(Feed):
    title = "Whats new on eventowl"
    link = '/feed/'
    description = "All your new concerts, book releases and everything else."

    def get_object(self, request, uuid):
        return UserProfile.objects.get(uuid=uuid).user

    def items(self, obj):
        return notifications.models.Notification.objects.filter(recipient=obj).order_by('-timestamp')

    def item_title(self, item):
        return item.verb

    def item_description(self, item):
        return item.description

    def item_link(self, item):
        url_name = item.data.get('url_name')
        return url_name


class CalendarView(View):
    def get(self, request, uuid):
        user = UserProfile.objects.get(uuid=uuid).user
        db_events = _subscribed_events(Artist, 'artists', Event, user).filter(
            city__iexact=user.userprofile.city)
        if 'postgres_disabled' in DATABASES['default']['ENGINE']:
            events = db_events.order_by(
                'date', 'time', 'venue').distinct('date', 'time', 'venue')
        else:
            seen = set()
            events = []
            for event in db_events:
                key = (event.date, event.time, event.venue)
                if key not in seen:
                    events.append(event)
                    seen.add(key)

        cal = icalendar.Calendar()
        for event in events:
            location = "{}, {}".format(event.venue.title(), event.city.title())
            summary = ", ".join(artist.name.title()
                                for artist in event.artists.all())
            duration = 120
            description = ""
            cal = ical_event(event.date, event.time, duration,
                             location, summary, description, cal)

        filename = 'events.ics'
        response = HttpResponse(cal.to_ical(), content_type='text/calendar')
        response['Filename'] = filename

eventowl/templates/eventowl/about.html
{% extends 'eventowl/base.html' %}
{% load static%}

{% block content %}
<legend>About EventOwl.<img src="{% static 'icons/eventowl.png' %}"></legend>
<b>EventOwl</b> aims to be your one stop solution to find everything that is fun around you.
You can find concerts of your <a href="{% url 'concertowl:show_artists' %}">favorite artists</a> around where you live.
And as we know better than you what kind of music you like, we of course also offer a <a href="{% url 'concertowl:recommendations' %}">artists recommendation</a>.<br/>
As life would pretty boring without books (or is it pretty boring with books in it?) we also tell you when your <a href="{% url 'bookowl:show_authors' %}">favorite authors</a> publish a new book.
Pretty nifty, huh?<br/>
So, please enjoy your stay here and have as much fun as possible!
{%endblock content %}

eventowl/templates/eventowl/base.html
{% extends 'eventowl/common_base.html' %}
{% load static %}


{% block navbar_style %}
    navbar-inverse
{% endblock navbar_style%}


{% block navbar_title %}
    <a href="/" class="pull-left"><img src="{% static 'icons/eventowl-white.png' %}"></a>
    <a class="navbar-brand" href="/">EventOwl</a>
{% endblock navbar_title %}


{% block extra_header %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'eventowl.css' %}">
    <meta name="theme-color" content="#000000">
{% endblock extra_header %}

eventowl/templates/eventowl/choice.html
{% extends 'eventowl/base.html' %}
{% load static%}

{% block content %}
<legend>Welcome to EventOwl</legend>
We provide several services to keep track of all the fun aspects of your life.<br>
<div class="container">
    <div class="row row-centered">
        <div class="col-md-4 col-centered">
            <a href="{% url 'bookowl:show_events' %}"><font size="12"><i class="fa fa-leanpub"></i> Books</font></a>
        </div>
        <div class="col-md-4 col-centered">
            <a href="{% url 'concertowl:show_events' %}"><font size="12"><i class="fa fa-music"></i> Concerts</font></a>
        </div>
        <div class="col-md-4 col-centered">
            <a href="{% url 'concertowl:show_records' %}"><font size="12"><i class="glyphicon glyphicon-cd"></i> Records</font></a>
        </div>
    </div>
</div>
{%endblock content %}

eventowl/templates/eventowl/common_base.html
{% load static %}
{% load notifications_tags %}
{% load common_tags %}

<html>
	<head> <title>EventOwl</title>
		<meta name="description" content="The one stop solution to find everything that is fun around you. Including new books by you favorite authors on concerts in your city" />
		<meta name="keywords" content="concerts,books,authors,artists,fun,city,events" />
        <meta name="msvalidate.01" content="79501FFCB680247BC9DE3C96D910AE66" />
		<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'common.css' %}">

        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'jquery/jExpand.js' %}"></script>
        <script src="{% static 'django_js_reverse/js/reverse.js' %}"></script>
        <script src="{% static 'utils.js' %}" type="text/javascript"></script>
        <script src="{% static 'custom_notifcations.js' %}" type="text/javascript"></script>
        <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
        <script>
            notify_badge_id='live_notify_badge';
            notify_menu_id='live_notify_list';
            notify_api_url='/inbox/notifications/api/unread_list/';
            notify_fetch_count='5';
            notify_unread_url='/inbox/notifications/unread/';
            notify_mark_all_unread_url='/inbox/notifications/mark-all-as-read/';
            notify_refresh_period=5000;
            register_notifier(fill_notification_list_with_link);register_notifier(fill_notification_badge);
        </script>
		<!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-71846670-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-71846670-1 ');
        </script>

        <meta name="viewport" content="width=device-width, initial-scale=1" />
		{% block extra_header %}
        {% endblock %}
	</head>

<body onLoad="addWhitespace();">
	<nav class="navbar {% block navbar_style %}{% endblock %} navbar-fixed-top" role="navigation">
	  <div class="container-fluid">
		  <div class="navbar-header">
			  {% block navbar_title %}
              {% endblock %}
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse" aria-expanded="false" aria-controls="navbar">
				  <span class="sr-only">Toggle navigation</span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
			  </button>
		  </div>

		  <div class="collapse navbar-collapse" id="collapse">
              <ul class="nav navbar-nav">
                  {% block navbar %}
                  {% endblock %}
              </ul>

			  <ul class="nav navbar-nav navbar-right">
				<li> <a href="{% url 'eventowl:impressum' %}">Impressum</a></li>
				<li> <a href="{% url 'eventowl:about' %}">About</a></li>
				{% if user.is_authenticated %}
				   <li class="dropdown">
				   	   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				   	   		Notifications <span id="live_notify_badge" class="badge">{% notifications_unread %}</span>
				   	   </a>
					   <ul class="dropdown-menu" role="menu" id="notification-menu">
					   </ul>
				   </li>
				   <li class="dropdown">
					   <a href="#" class="dropdown-toggle" data-toggle="dropdown"> {{ user.username }} <b class="caret"></b></a>
					   <ul class="dropdown-menu" role="menu">
							<li><a href="{% url 'account_settings' %}">Settings</a></li>
							<li><a href="{% url 'logout' %}">Log out</a></li>
					  </ul>
				   </li>
				{%endif%}
			  </ul>
			</div>
	   </div>
	</nav>

    <div class="content container" id="content_div">
        <div class="jumbotron">
	        {% block content %}
	        {% endblock %}
        </div>
    </div>

</body>
</html>

eventowl/templates/eventowl/filter.html
{% load common_tags %}

<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
  <input id="id_filter"
       class="form-control"
       placeholder="Filter..."
       value="{{ request.GET|get_item:'name_filter'|default:'' }}"
       name="name_filter"
       type="text">
  <span class="input-group-btn">
    <button class="btn btn-default" type="submit">Go!</button>
  </span>
</div>

eventowl/templates/eventowl/pagination.html
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == page%}
                <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
             {% else %}
                <li><a href="?page={{ page }}">{{ page }}</a></li>
             {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}

eventowl/templates/eventowl/profile.html
{% extends 'eventowl/base.html' %}

{% load widget_tweaks %}

{% block content %}
<legend>We need some more information about you (nothing indiscreet, we promise).</legend>
<form id="social_form" method="post">
    {% csrf_token %}
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
            {{ form.city|add_class:"form-control"|attr:"placeholder:Event city" }}
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Log in</button>
</form>
    
{% if form.errors %}
    {% for field_name, error in form.errors.items %}
        <p><i>Sorry, but we have a problem with the field {{ field_name }}: {{ error|striptags }} </i></p>
    {% endfor %}   
{% endif %}

{% endblock %}