bookowl/urls.py
from django.conf.urls import url
from bookowl import views

app_name = 'bookowl'

urlpatterns = [
    url(r'^$', views.EventsView.as_view(), name='show_events'),
    url(r'^add_authors/$', views.AddAuthorsView.as_view(), name='add_authors'),
    url(r'^calibre/$', views.UploadCsv.as_view(), name='calibre'),
    url(r'^show_authors/$', views.AuthorsView.as_view(), name='show_authors'),
    url(r'^recommendations/$', views.EventsView.as_view(), name='recommendations'),
]

concertowl/urls.py
from django.conf.urls import url
from concertowl import views

app_name = 'concertowl'

urlpatterns = [
    url(r'^upload_json/$', views.upload_json, name='upload_json'),
    url(r'^upload_local/$', views.UploadLocalView.as_view(), name='upload_local'),
    url(r'^spotify/$', views.spotify, name='spotify'),
    url(r'^show_artists/$', views.ArtistsView.as_view(), name='show_artists'),
    url(r'^show_records/$', views.RecordsView.as_view(), name='show_records'),
    url(r'^add_artists/$', views.AddArtistsView.as_view(), name='add_artists'),
    url(r'^recommendations/$', views.RecommendationsView.as_view(),
        name='recommendations'),
    url(r'^$', views.EventsView.as_view(), name='show_events'),
]

eventowl/urls.py
from django.conf.urls import url
from eventowl import views

app_name = 'eventowl'

urlpatterns = [
    url(r"^$", views.ChoiceView.as_view(), name="choice"),
    url(r"^impressum/$", views.ImpressumView.as_view(), name="impressum"),
    url(r"^about/$", views.AboutView.as_view(), name="about"),
    url(r"^ical/$", views.ICalView.as_view(), name="ical"),
    url(
        r"^account/signup/$",
        views.SignupView.as_view(),
        name="account_signup"
    ),
    url(
        r"^account/settings/$",
        views.SettingsView.as_view(),
        name="account_settings"
    ),
    url(r'^feed/(?P<uuid>[\da-f-]+)/$',
        views.NotificationsFeed(), name="feed"),
    url(r'^calendar/(?P<uuid>[\da-f-]+)/$',
        views.CalendarView.as_view(), name="calendar"),
]

eventowlproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from notifications import urls as notification_urls

urlpatterns = [
    url(r'^', include('eventowl.urls', 'eventowl')),
    url(r'^artists/', include('concertowl.urls', 'concertowl')),
    url(r'^books/', include('bookowl.urls', 'bookowl')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^account/', include('account.urls')),
    url('^inbox/notifications/', include(notification_urls, namespace='notifications')),
]

concertowl/models.py
from django.db import models
from django.contrib.auth.models import User
from eventowl import models as base_models


class Artist(models.Model):
    name = models.CharField(max_length=200)
    genre = models.CharField(max_length=200, null=True)
    subscribers = models.ManyToManyField(User, related_name='artists')
    recommendedtos = models.ManyToManyField(User, through='RecommendedArtist')
    favoritedby = models.ManyToManyField(User, related_name='favorit_artists')

    def __str__(self):
        return self.name


class RecommendedArtist(models.Model):
    artist = models.ForeignKey(
        Artist, related_name="recommendation", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField(null=True)


class Event(models.Model):
    venue = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    date = models.DateField()
    time = models.TimeField()
    ticket_url = models.URLField()
    artists = models.ManyToManyField(Artist, related_name='events')

    def __str__(self):
        artist_names = [artist.name.title() for artist in
                        self.artists.all()]
        name = "{} at {} on {}".format(", ".join(artist_names),
                                       str(self.venue),
                                       str(self.date.strftime("%Y-%m-%d")))
        return name


class Preview(base_models.Preview):
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)


class Record(models.Model):
    title = models.CharField(max_length=500)
    date = models.DateField()
    details_url = models.URLField(max_length=500)
    artists = models.ManyToManyField(Artist, related_name='releases')

    def __str__(self):
        artist_names = [artist.name.title() for artist in
                        self.artists.all()]
        name = "{} by {} on {}".format(self.title,
                                       ", ".join(artist_names),
                                       str(self.date.strftime("%Y-%m-%d")))
        return name

concertowl/forms.py
from eventowlproject import settings
from eventowl.forms import RestrictedFileField

from django import forms

class UploadFileForm(forms.Form):
    artists = RestrictedFileField(content_types=['application/json'],
                                  max_upload_size=settings.MAX_UPLOAD_SIZE)

concertowl/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from .models import Event, Artist, Record
from eventowl import views as baseviews
from eventowl.utils.string_helpers import parse_json
from concertowl.forms import UploadFileForm
from concertowl.utils import model_helpers
from eventowlproject import settings
from concertowl.api_calls.spotify import spotify_auth_url, spotify_token_from_code
from concertowl.tasks import spotify_artists, update_recommended_artists


def _user_events(user):
    artists = Artist.objects.filter(subscribers=user)
    events = Event.objects.filter(artists=artists).distinct()
    return events


@login_required
def spotify(request):
    if request.GET.get('import') is not None:
        auth_url, state = spotify_auth_url()
        request.session["state"] = state
        return redirect(auth_url)

    if request.GET.get('code') is not None:
        code = request.GET.get('code')
        state = request.GET.get('state')
        if request.session.get("state") != state:
            print("Oh noes...")
        token_info = spotify_token_from_code(code)
        request.session["token"] = token_info["access_token"]
        request.session["refresh_token"] = token_info["refresh_token"]
        spotify_artists.delay(token_info["access_token"])
        return render(request, 'concertowl/spotify_running.html')

    return render(request, 'concertowl/spotify.html')


class EventsView(baseviews.EventsView):
    template_name = 'concertowl/show_events_table.html'
    event_model = Event
    originator_model = Artist
    originator_name = 'artists'

    def _filtered_and_sorted(self, name_filter, user):
        pre_filtered = super(self.__class__, self)._filtered_and_sorted(
            name_filter, user)
        return pre_filtered.filter(city__iexact=user.userprofile.city)


class RecordsView(baseviews.EventsView):
    template_name = 'concertowl/show_records_table.html'
    event_model = Record
    originator_model = Artist
    originator_name = 'artists'
    override_days_back = 365


class ArtistsView(baseviews.OriginatorView):
    template_name = 'concertowl/show_artists.html'
    context_object_name = 'artists'
    update_recommendation_func = update_recommended_artists
    originator_model = Artist


class RecommendationsView(baseviews.CustomListView):
    template_name = 'concertowl/recommendations.html'
    context_object_name = 'artists'

    def get(self, request):
        new_artist = request.GET.get("new_artist")
        if new_artist is not None:
            model_helpers.update_artists([new_artist], request.user)

        return baseviews.CustomListView.get(self, request)

    def _filtered_and_sorted(self, name_filter, user):
        _recommended_artists = Artist.objects.filter(recommendedtos=user,
                                                     name__icontains=name_filter).exclude(subscribers=user)
        return _recommended_artists.order_by('-recommendation__score')


class AddArtistsView(baseviews.AddView):
    template_name = 'concertowl/add_artists.html'

    def update_func(self, *args, **kwargs):
        return model_helpers.update_artists(*args, **kwargs)


def _parse_json_file(request):
    try:
        parsed = parse_json(request.FILES["artists"].read().decode("utf8"))
    except ValueError:
        parsed = []
    return parsed


@login_required
def upload_json(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            artists = _parse_json_file(request)
            model_helpers.update_artists(artists, request.user)
            artists_str = ', '.join(sorted(artists))
            return render(request,
                          'concertowl/update_result.html',
                          {'artists': artists_str,
                           'source': 'JSON upload'})
    else:
        form = UploadFileForm()
    return render(request,
                  'concertowl/upload_json.html',
                  {'form': form,
                   'max_size_mb': settings.MAX_UPLOAD_SIZE / 1024 ** 2})


class UploadLocalView(TemplateView):
    template_name = 'concertowl/upload_local.html'

concertowl/templates/concertowl/add_artists.html
{% extends 'concertowl/base.html' %}
{% block content %}

<legend>Add new artists manually. How very old school.</legend>
<form action="{% url 'concertowl:add_artists' %}" method="get">
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-music"></i></span>
      <input id="id_filter"
           class="form-control"
           placeholder="New artist..."
           name="add"
           type="text">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Add!</button>
      </span>
    </div>
</form>

{% if request.GET.add %}
Sucesfully added {{ request.GET.add|title }}. Maybe they have an <a href="{% url 'concertowl:show_events' %}">event</a> soon?
{% endif %}

{% endblock content %}

concertowl/templates/concertowl/base.html
{% extends 'eventowl/common_base.html' %}
{% load static %}


{% block extra_header %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-concert-theme.css' %}">
    <link rel="stylesheet" href="{% static 'concertowl.css' %}">
    <meta name="theme-color" content="#4b7b4c">
    {% block more_extra_header %}
    {% endblock %}
{% endblock extra_header %}


{% block navbar_style %}
    navbar-default
{% endblock navbar_style%}


{% block navbar_title %}
    <a href="/" class="pull-left"><img src="{% static 'icons/eventowl-white.png' %}"></a>
    <a style="padding:15 0 10 10; margin:0;" class="navbar-brand" href="/">EventOwl/</a>
    <a style="padding:15 10 10 0; margin:0;" class="navbar-brand" href="{% url 'concertowl:show_events' %}">ConcertOwl</a>
{% endblock navbar_title %}


{% block navbar %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Add artists <b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'concertowl:spotify' %}">Spotify</a></li>
            <li><a href="{% url 'concertowl:upload_local' %}">Local library</a></li>
            <li><a href="{% url 'concertowl:upload_json' %}">Upload JSON</a></li>
            <li><a href="{% url 'concertowl:add_artists' %}">Manually</a></li>
            <li><a href="{% url 'concertowl:recommendations' %}">Recommendations</a></li>
        </ul>
    </li>
    <li><a href="{% url 'concertowl:show_artists' %}">Show Artists</a></li>
    <li><a href="{% url 'concertowl:show_events' %}">Show Events</a></li>
    <li><a href="{% url 'concertowl:show_records' %}">Show Records</a></li>
{% endblock navbar %}

concertowl/templates/concertowl/recommendations.html
{% extends 'concertowl/base.html' %}
{% block content %}

<legend>Based on what you favorited (yes, we are watching) you might like these artists too.</legend>
<form action="{% url 'concertowl:recommendations' %}" method="get">
    {% include "eventowl/filter.html"%}
</form>

{% if artists %}
    <form action="{% url 'concertowl:recommendations' %}" method="get">
    <ul class="list-group">
    <button type="submit" style="display:none;"></button>
    {% for artist in artists %}
        <li class="list-group-item">
        {{ artist.name|title }}
        {% if artist.genre %}({{artist.genre|title}}) {% endif %}
        <button type="submit" class="btn btn-xs pull-right" name="new_artist" value="{{ artist.name }}">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        </li>
    {% endfor %}
    </ul>
    </form>
{% include "eventowl/pagination.html"%}

{% else %}
    {% if request.GET.filter%}
        <p>No artists matching {{ request.GET.filter }}.</p>
    {% else %}
        <p>There are no new recommendations for you. Sorry...<br>
        Maybe you want to favorite some more artists (it's the little star besides the artist name).</p>
    {% endif %}
{% endif %}

{% endblock content %}

concertowl/templates/concertowl/show_artists.html
{% extends 'concertowl/base.html' %}
{% block content %}

<legend>Have a look at all your subscribed artists.</legend>
<form action="{% url 'concertowl:show_artists' %}" method="get">
    {% include "eventowl/filter.html"%}
</form>

{% if artists %}
    <ul class="list-group">
    {% for artist in artists %}
        <li class="list-group-item">
	        {{ artist.name|title }}
	        <button type="button" class="btn btn-xs pull-right" name="remove" value="{{ artist.name }}" onclick="$.get(window.location.pathname + '?remove={{ artist.name|urlencode }}'); $(this).parent().hide()">
	            <span class="glyphicon glyphicon-remove"></span>
	        </button>
            <button type="button" id="unfavorite_{{ forloop.counter }}" class="btn btn-xs pull-right" name="unfavorite" value="{{ artist.name }}" onclick="$.get(window.location.pathname + '?unfavorite={{ artist.name|urlencode }}'); $(this).hide(); $('#favorite_{{ forloop.counter }}').show()">
                 <font color="DarkOrange"><span class="glyphicon glyphicon-star"></span></font>
            </button>
            <button type="button" id="favorite_{{ forloop.counter }}" class="btn btn-xs pull-right" name="favorite" value="{{ artist.name }}" onclick="$.get(window.location.pathname + '?favorite={{ artist.name|urlencode }}'); $(this).hide(); $('#unfavorite_{{ forloop.counter }}').show()">
                 <span class="glyphicon glyphicon-star"></span>
            </button>
            {% if artist in favorites %}
                <script>$('#favorite_{{ forloop.counter }}').hide()</script>
	        {% else %}
                 <script>$('#unfavorite_{{ forloop.counter }}').hide()</script>
	        {% endif %}
        </li>
    {% endfor %}
    </ul>
{% include "eventowl/pagination.html"%}

{% else %}
    {% if request.GET.name_filter%}
        <p>No artists matching '{{ request.GET.name_filter }}'.</p>
    {% else %}
        <p>You are not subscribed to any artists yet. Add some :)</p>
    {% endif %}
{% endif %}

{% endblock content %}

concertowl/templates/concertowl/show_events_table.html
{% extends 'concertowl/base.html' %}
{% load common_tags %}

{% block content %}
<legend>All your events. We hope you find something nice.</legend>

<form action="{% url 'concertowl:show_events' %}" method="get">
    {% include "eventowl/filter.html"%}
</form>

{% if events %}
      <table class="table table-hover table-striped" id=events-table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Artists</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for event in events %}
          {% with artists=event.artists.all|concat:", " %}
            <tr>
                <td>{{event.date|date}}</td>
                <td>
                 {{ artists }}
                 </td>
                 <td>
                    <a href="{% url 'eventowl:ical' %}?start_date={{ event.date|date:'U' }}&start_time={{ event.time|time:'H:i' }}&duration=120&summary={{ artists }}&location={{ event.venue|title }}, {{ event.city|title }}"
                       class="btn btn-xs pull-right" name="ical">
                        <span class="fa fa-calendar"></span>
                    </a>
                </td>
           </tr>
           <tr>
             <td colspan="3">
               This event by {{ artists }} is going to take place at <b>{{event.venue}}</b> in <b>{{event.city}}</b> ({{event.country}}).<br>
               Be there at <b>{{event.time}}</b> on <b>{{event.date}}</b>.<br>
               You can book your tickets <a href={{event.ticket_url}} target="_blank">here</a>.<br>
               <i>Enjoy :)</i>
          </td>
          </tr>
          {% endwith %}
         {% endfor %}
        </tbody>
      </table>


<script type="text/javascript">
$('#events-table').jExpand();
</script>

{% include "eventowl/pagination.html" %}

{% else %}
    {% if request.GET|get_item:'name_filter'|default:'' %}
        <p>No events matching '{{ request.GET.name_filter }}'.</p>
    {% else %}
        <p>Your <a href="{% url 'concertowl:show_artists' %}">subscribed artists</a> don't have events any time soon :(</p>
    {% endif %}
{% endif %}

{% endblock content %}

concertowl/templates/concertowl/show_records_table.html
{% extends 'concertowl/base.html' %}
{% load common_tags %}

{% block content %}
<legend>The newest records of all your favorite artists.</legend>

<form action="{% url 'concertowl:show_records' %}" method="get">
    {% include "eventowl/filter.html"%}
</form>

{% if events %}
      <table class="table table-hover table-striped" id=events-table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Artists</th>
            <th>Release Date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for event in events %}
          {% with artists=event.artists.all|concat:", " %}
            <tr>
                <td>{{event.title|title}}</td>
                <td>{{ artists }}</td>
                <td>{{event.date|date}}</td>
                 <td>
                    <a href="{% url 'eventowl:ical' %}?start_date={{ event.date|date:'U' }}&summary={{ event.title|title }}&whole_day=1"
                           class="btn btn-xs pull-right" name="ical">
		    	            <span class="fa fa-calendar"></span>
                        </a>
                </td>
           </tr>
           <tr>
             <td colspan="4">
               The album <b>{{event.title|title}}</b> by <b>{{artists}}</b> is going to be released on <b>{{event.date}}</b>.<br>
               You can get more information <a href={{event.details_url}} target="_blank">here</a>.<br>
               <i>Let's hope it's a good one.</i>
          </td>
          </tr>
          {% endwith %}
         {% endfor %}
        </tbody>
      </table>


<script type="text/javascript">
$('#events-table').jExpand();
</script>

{% include "eventowl/pagination.html" %}

{% else %}
    {% if request.GET|get_item:'name_filter'|default:'' %}
        <p>No records matching '{{ request.GET.name_filter }}'.</p>
    {% else %}
        <p>Your <a href="{% url 'concertowl:show_artists' %}">subscribed artists</a> don't have records any time soon :(</p>
    {% endif %}
{% endif %}

{% endblock content %}

concertowl/templates/concertowl/spotify.html
{% extends 'concertowl/base.html' %}
{% block content %}
<legend>Import new artitsts from spotify. How very extraordinary.</legend>
<p>This really might take a while, especially for a larger library. So sit back and enjoy.</p>
<form action="{% url 'concertowl:spotify' %}" method="get">
	<span class="input-group-btn">
	    <button class="btn btn-primary" id="import" type="submit" name="import" value="true">Import</button>
	</span>
</form>

<script>
$('#import').click(function(){
    var $this = $(this);
    $this.text('Importing...');
});
</script>

{% endblock content %}

concertowl/templates/concertowl/spotify_running.html
{% extends 'concertowl/base.html' %}
{% block content %}
<legend>Currently importing new artitsts from spotify...</legend>
<p>We said it's going to take a while, right? You can use the site normally in the meantime, but keep an eye on your notifications, there you will see when it's all done.</p>

{% endblock content %}

concertowl/templates/concertowl/update_result.html
{% extends 'concertowl/base.html' %}
{% block content %}
<legend>Import result</legend>
{% if artists %}
Updated artists using {{ source }}.
<br><br>
Got:<br>
{{ artists }}.
{% else %}
Could not find any artists.
{% endif %}
{%endblock content %}

concertowl/templates/concertowl/upload_json.html
{% extends 'concertowl/base.html' %}
{% load widget_tweaks %}
{% load static%}

{% block more_extra_header %}
<script src="{% static 'jquery/bootstrap-filestyle.min.js' %}"></script>
{% endblock more_extra_header %}

{% block content %}
<legend>Upload a json file with new artists. How very fancy.</legend>
<p>This file should be in json format and contain a list of artist names that you want to add. Please keep it under {{max_size_mb}}MB, thanks.</p>
<form class="form-inline" enctype="multipart/form-data" method="post" action="{% url 'concertowl:upload_json' %}">
{% csrf_token %}
<div class="form-group">
<div class="input-group">
    {{ form.artists|add_class:"filestyle"}}
</div>
<button type="submit" class="btn btn-primary">Upload</button>
</form>

{% if form.errors %}
<p><i>Could not upload file: {{ form.errors.artists|striptags }}</i></p>
{% endif %}

{%endblock content %}

concertowl/templates/concertowl/upload_local.html
{% extends 'concertowl/base.html' %}
{% load static%}

{% block more_extra_header %}
<script src="{% static 'id3.min.js' %}"></script>
<script src="{% static 'jquery/bootstrap-filestyle.min.js' %}"></script>
{% endblock more_extra_header %}

{% block content %}
<legend>Scan your local library without actually uploading anything. That's something now, isn't it?</legend>
<p>In very modern browsers you can select a directory and we will find every artists in there. In just regularly modern browsers, you'll have to select multiple files manually, sorry.</p>
<input type="file" id="filepicker" class="filestyle" data-input="false" data-buttonText="Choose directory or files" name="fileList" webkitdirectory multiple />
<span id="resulttext"></span>

<script>
    document.getElementById("filepicker").addEventListener("change", function(event) {
        let files = event.target.files;
        let item = document.getElementById("resulttext");
        item.innerHTML = "Found " + files.length + " files. Figuring out the artists now. Please stay on the page for now.";

        let artists = [];
        for (let i=0; i<files.length; i++) {
            id3(files[i], function(err, tags) {
                artists.push(tags.artist);
                if (i === files.length - 1) {
                    collected_artists(artists)
                }
            });
        };
    }, false);

    function collected_artists(artists) {
        let unique_artists = unique(artists);

        let item = document.getElementById("resulttext");
        item.innerHTML = "Found " + unique_artists.length + " unique artists, adding them now. Feel free to leave the page now.";

        base_url = Urls["concertowl:add_artists"]()
        add_url = base_url + "?add=" + unique_artists.join()
        $.get(add_url, function (data) {
            item.innerHTML = "Found and added " + unique_artists.length + " unique artists. Have fun!";
        });
    }
</script>
{%endblock content %}